import os
import sys
import json

# Fix Windows console encoding
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CATALOG_PATH = os.path.join(BASE_DIR, "dynamic_catalog.json")

# 60 Elite, Distinct, High-Value, Zero-Duplicate Financial Blueprints
# Each has real numbers, laws, circulars, or contrarian wealth mechanics
ELITE_EXPANSION = [
    {
        "id": 21,
        "region": "GLOBAL",
        "category": "Banking Shield",
        "voice": "en-US-ChristopherNeural",
        "title": "The FDIC $250,000 Loophole (Insure Up to $3 Million) 🏦🛡️ #BankingSecrets",
        "sub": "How high-net-worth individuals insure millions without opening 12 different banks",
        "c1_t": "THE $250K LIMIT RISK",
        "c1_d": "Most people assume all cash in their bank is safe. In reality, the FDIC only protects up to $250,000 per depositor per institution. Any dollar above that is uninsured in a bank run.",
        "b1": "warning",
        "c2_t": "THE INTRAFI / CDARS NETWORK",
        "c2_d": "Step 1: Ask your private or community bank for IntraFi Sweep (CDARS).\nStep 2: Your bank breaks deposits into $240,000 chunks across 50 partner banks.\nStep 3: You manage 1 single account while getting multi-million FDIC coverage.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "100% Federal Insurance Protection up to $3M+\nSingle statement and single 1099-INT tax form.",
        "b3": "money",
        "script": "If you keep more than 250,000 dollars in a single bank account, you are taking a massive financial risk. The government only insures up to 250K per bank. Billionaires never open 15 separate bank accounts to stay insured. Instead, they use a free banking protocol called IntraFi. You deposit your funds into one primary bank, and their system automatically sweeps your cash into 240,000 dollar chunks across dozens of network banks. You get up to 3 million dollars in full federal insurance while managing one single login. Save this reel so you never risk your capital.",
        "tags": ["fdc insurance", "banking secrets", "cdars sweep", "wealth protection", "high net worth", "money tips"],
        "pinned_comment": "Did you know about the IntraFi network? Comment below to get our High-Yield Wealth Masterlist!"
    },
    {
        "id": 22,
        "region": "INDIA",
        "category": "Tax Arbitrage",
        "voice": "en-IN-PrabhatNeural",
        "title": "The HUF Tax Loophole: Save ₹1,50,000+ Every Year 🇮🇳🏛️ #TaxSavings",
        "sub": "How Indian business owners and families legally create a second tax-free identity",
        "c1_t": "THE SINGLE PAN TAX TRAP",
        "c1_d": "Filing taxes solely under your personal PAN card pushes your income into the 30% tax bracket rapidly. You lose lakhs to income tax on rental yields and capital gains.",
        "b1": "warning",
        "c2_t": "CREATE A HINDU UNDIVIDED FAMILY (HUF)",
        "c2_d": "Step 1: If married, establish an HUF with your spouse and children.\nStep 2: Obtain a separate legal PAN card and bank account for the HUF.\nStep 3: Gift or route ancestral property and investments through the HUF.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Fresh ₹7,00,000 0% Tax Slab under New Tax Regime\nAdditional ₹1,50,000 Section 80C deduction under Old Regime.",
        "b3": "money",
        "script": "If you earn over 15 lakh rupees a year in India, you are overpaying taxes if you only use one PAN card. Under Indian tax law, any married Hindu, Sikh, Jain, or Buddhist can legally create an HUF—a Hindu Undivided Family. An HUF gets its own separate PAN card and distinct tax entity status. That gives your household a second zero-tax basic exemption slab of up to 7 lakh rupees under the new tax regime. You can route rental income, family investments, and stock capital gains through this second PAN card to legally save over 1.5 lakh rupees every year. Share this with your family and follow for more.",
        "tags": ["huf tax", "save income tax", "huf pan card", "indian tax law", "wealth blueprint", "smart tax"],
        "pinned_comment": "Are you using an HUF for family taxes? Comment below and follow The Wealth Blueprint!"
    },
    {
        "id": 23,
        "region": "GLOBAL",
        "category": "Credit Strategy",
        "voice": "en-US-ChristopherNeural",
        "title": "The Zero-Liability Chargeback Rule (Force Instant Merchant Refunds) 💳⚡",
        "sub": "The federal consumer protection law that guarantees refunds when merchants scam you",
        "c1_t": "THE DEBIT CARD DANGER",
        "c1_d": "When you buy goods with a debit card, real cash leaves your checking account instantly. If a vendor ghosts you or sends damaged goods, your money is gone for weeks while banks 'investigate'.",
        "b1": "warning",
        "c2_t": "FAIR CREDIT BILLING ACT (FCBA)",
        "c2_d": "Step 1: Always use a major credit card for purchases over $50.\nStep 2: If a seller refuses a refund, call card issuer and invoke 'Fair Credit Billing Chargeback'.\nStep 3: The bank legally claws back the merchant's payment instantly.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "100% Financial Insulation from Fraud\nMerchant bears the burden of proof, not you.",
        "b3": "money",
        "script": "Never buy anything online or book a flight using a debit card. When you use a debit card, your own hard-earned cash is deducted immediately. If a merchant sends a defective product or refuses a refund, good luck fighting them. But when you use a credit card, you are protected under federal Fair Credit Billing laws. The moment a merchant acts dishonestly, call your bank and request a formal chargeback. The credit card company immediately reverses the charge and pulls the funds directly from the merchant's account. The merchant is guilty until proven innocent. Save this reel to protect your wallet.",
        "tags": ["chargeback hack", "credit card protection", "consumer rights", "avoid scams", "money rules", "wealth blueprint"],
        "pinned_comment": "Ever had to file a chargeback? Tell us below and follow for zero-BS wealth loopholes!"
    },
    {
        "id": 24,
        "region": "INDIA",
        "category": "Investing Loophole",
        "voice": "en-IN-PrabhatNeural",
        "title": "SGB Secondary Market Hack: Buy 24K Gold at an 8% Discount 🪙📉",
        "sub": "How smart investors buy Sovereign Gold Bonds below spot gold prices on NSE",
        "c1_t": "BUYING PHYSICAL GOLD TRAP",
        "c1_d": "Jewelers charge 10% to 25% making charges on physical jewelry, plus 3% GST. You immediately lose 15% to 28% of your money the second you walk out of the store.",
        "b1": "warning",
        "c2_t": "THE NSE SECONDARY MARKET SGB HACK",
        "c2_d": "Step 1: Open Zerodha, Groww, or AngelOne and search for existing SGB ticker codes.\nStep 2: Look for low-liquidity tranches trading at 5% to 8% below current spot gold prices.\nStep 3: Buy the discounted tranches and hold until RBI maturity.",
        "b2": "growth",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Instant 5% to 8% Discount on Pure Gold\n+2.5% Annual Interest + 0% Capital Gains Tax at maturity!",
        "b3": "bull",
        "script": "Stop buying physical gold jewelry if your goal is investment. Making charges and GST eat up up to 20 percent of your capital on day one. Instead, use the Sovereign Gold Bond secondary market glitch. On the National Stock Exchange, existing SGBs trade daily like shares. Because many retail investors panic-sell for urgent cash, certain SGB series trade at a 5 to 8 percent discount compared to live 24-karat gold rates. You can buy gold cheaper than market price, earn 2.5 percent guaranteed annual interest from the government, and pay zero percent capital gains tax upon maturity. Save this before the market catches on.",
        "tags": ["sgb gold bond", "buy gold cheap", "nse gold loophole", "indian investing", "zerodha hack", "wealth blueprint"],
        "pinned_comment": "Are you investing in SGBs or physical gold? Comment your strategy below!"
    },
    {
        "id": 25,
        "region": "GLOBAL",
        "category": "Wealth Compounding",
        "voice": "en-US-ChristopherNeural",
        "title": "The Step-Up SIP Secret: Double Your Net Worth in 15 Years 📈🚀",
        "sub": "Why adding just 10% to your monthly investment generates ₹1.5 Crore in extra wealth",
        "c1_t": "THE FLAT SIP MISTAKE",
        "c1_d": "Investing a fixed $500 or ₹10,000 every month for 20 years ignores career salary growth and inflation. You leave hundreds of thousands of compounding dollars on the table.",
        "b1": "warning",
        "c2_t": "THE 10% STEP-UP FORMULA",
        "c2_d": "Step 1: Start with your baseline monthly SIP (e.g. ₹10,000/month).\nStep 2: Enable 'Annual Step-Up' of 10% to match your annual appraisal/raise.\nStep 3: Year 2 becomes ₹11,000, Year 3 becomes ₹12,100 on autopilot.",
        "b2": "growth",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Standard SIP at 12%: ₹99.9 Lakhs\n10% Step-Up SIP at 12%: ₹2.33 CRORE! (+₹1.33 Crore extra profit).",
        "b3": "bull",
        "script": "If you invest the same flat amount into index funds every month for 15 years, you are quietly sabotaging your retirement wealth. As your career grows, your investments should scale automatically. Enter the 10 percent Step-Up SIP. If you invest 10,000 rupees a month at a 12 percent return, you end up with roughly 1 crore rupees in 20 years. But if you activate a 10 percent annual step-up—adding just 1,000 rupees more per month each year as your salary increases—your total wealth explodes to over 2.3 crore rupees. That is 1.3 crore in pure bonus wealth with zero lifestyle sacrifice. Save this reel and set up your step-up today.",
        "tags": ["step up sip", "compound interest", "how to build wealth", "mutual fund formula", "investing math", "wealth blueprint"],
        "pinned_comment": "Have you turned on the 10% Step-Up toggle in your investment app? Comment below!"
    },
    {
        "id": 26,
        "region": "INDIA",
        "category": "Banking Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "RBI Bank Locker Compensation Rule: 100x Rent Guarantee 🏦🔐",
        "sub": "The mandatory central bank rule that forces banks to reimburse you if your locker is looted",
        "c1_t": "THE BANK DISCLAIMER LIE",
        "c1_d": "Bank managers routinely tell customers: 'We are not responsible for what happens to your locker in a fire or theft.' Most people surrender their rights believing this myth.",
        "b1": "warning",
        "c2_t": "RBI MANDATORY LOCKER CIRCULAR",
        "c2_d": "Step 1: Check RBI Circular DOR.LEG.REC/40/09.07.005/2021-22.\nStep 2: In incidents of fire, theft, burglary, or building collapse due to bank negligence:\nStep 3: The bank is legally mandated to pay 100 TIMES the annual locker rent as damages.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Guaranteed Legal Compensation of 100x Annual Rent\nBank cannot disown liability under contract law.",
        "b3": "money",
        "script": "Never let your bank tell you they have zero liability for your safe deposit locker. In the past, banks made customers sign abusive agreements saying they weren't responsible for theft or fire. The Reserve Bank of India stepped in with a strict directive: if your bank locker is compromised due to fire, robbery, building collapse, or staff fraud, the bank cannot wash its hands. Under RBI rules, the bank must pay compensation equal to one hundred times your annual locker rent. If your rent is 5,000 rupees, they owe you 5 lakh rupees immediately. Share this with your parents and follow The Wealth Blueprint.",
        "tags": ["rbi rules", "bank locker compensation", "indian banking law", "consumer protection", "safe deposit box", "wealth blueprint"],
        "pinned_comment": "Does your family have a bank locker? Save this reel for legal protection!"
    },
    {
        "id": 27,
        "region": "GLOBAL",
        "category": "Tech Arbitrage",
        "voice": "en-US-ChristopherNeural",
        "title": "NotebookLM: Turn Dense 100-Page PDFs into 2-Person AI Podcasts 🎙️📄",
        "sub": "How to master complex financial annual reports & contracts in 5 minutes",
        "c1_t": "THE 100-PAGE REPORT TRAP",
        "c1_d": "Reading 200-page corporate financial 10-Ks, legal contracts, or investment prospectuses takes 8+ hours. 99% of investors give up and make blind decisions.",
        "b1": "warning",
        "c2_t": "GOOGLE NOTEBOOKLM AUDIO OVERVIEW",
        "c2_d": "Step 1: Go to notebooklm.google.com and upload your target financial PDF.\nStep 2: Click 'Generate Audio Overview' in the right studio panel.\nStep 3: Two AI hosts banter, break down key numbers, and explain risks in 6 minutes.",
        "b2": "growth",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Absorb 200 Pages of Complex Data in 6 Minutes\nFree tool backed by Gemini 1.5 Pro architecture.",
        "b3": "money",
        "script": "Reading 100-page investment reports and legal contracts is exhausting. Most people skip the fine print and lose thousands. Google built a free secret AI tool called NotebookLM that solves this completely. Upload any dense PDF—an annual financial filing, an insurance policy, or a complex tax code. Then click one button: Generate Audio Overview. Two AI hosts generate a natural, conversational 2-person podcast analyzing the document, highlighting red flags, and breaking down complex numbers in simple English. You can listen on your commute and understand any contract in 6 minutes. Save this reel and try it today.",
        "tags": ["notebooklm", "google ai", "ai productivity", "pdf to podcast", "gemini ai", "study hacks"],
        "pinned_comment": "Have you tried NotebookLM yet? Drop your favorite AI tool in the comments!"
    },
    {
        "id": 28,
        "region": "INDIA",
        "category": "Tax Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "Section 54F: Sell Stocks, Buy a Home, Pay 0% Capital Gains 🏠⚖️",
        "sub": "The legal tax exemption that lets you roll equity profits directly into residential property",
        "c1_t": "THE 20% LTCG TAX HIT",
        "c1_d": "Selling appreciated shares, mutual funds, or gold triggers 12.5% to 20% long-term capital gains tax. A ₹50 Lakh stock gain costs you up to ₹10 Lakhs in pure taxes.",
        "b1": "warning",
        "c2_t": "SECTION 54F EXEMPTION SHIELD",
        "c2_d": "Step 1: Ensure you do not own more than 1 residential house on sale date.\nStep 2: Reinvest the net sale proceeds into constructing or buying 1 new residential house.\nStep 3: Buy within 1 year before or 2 years after (3 years for construction).",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "100% Tax Exemption on Stock & Gold Gains up to ₹10 Crore!\nKeep your entire profit compounding in real estate.",
        "b3": "money",
        "script": "If you are sitting on massive profits in stocks, mutual funds, or gold, do not sell them before knowing Section 54F of the Income Tax Act. Normally, cashing out large equity gains triggers heavy long-term capital gains taxes. But Section 54F says if you reinvest the full net sales proceeds to buy or construct a residential house, your entire capital gains tax drops to exactly zero rupees. You can take 50 lakh or 1 crore rupees in stock market profits and roll it directly into your dream home without paying a single rupee to the tax department. Share this with an investor who needs this loophole.",
        "tags": ["section 54f", "capital gains tax", "save income tax", "real estate tax hack", "indian tax law", "wealth blueprint"],
        "pinned_comment": "Did you know you can avoid stock taxes with real estate? Comment below!"
    },
    {
        "id": 29,
        "region": "GLOBAL",
        "category": "Credit Strategy",
        "voice": "en-US-ChristopherNeural",
        "title": "The Retention Call Script: Waive ANY Credit Card Fee in 2 Minutes 📞💳",
        "sub": "The exact phrases credit card retention agents are authorized to grant fee waivers for",
        "c1_t": "PAYING ANNUAL FEES BLINDLY",
        "c1_d": "Millions of cardholders blindly pay $95 to $695 annual fees every year. Banks bank on customer passivity to collect billions in uncontested fee revenue.",
        "b1": "warning",
        "c2_t": "THE RETENTION SCRIPTS THAT WORK",
        "c2_d": "Step 1: Call the number on the back of your card and say 'Cancel my card'.\nStep 2: Transfer to the Retention Department (they have spending authority).\nStep 3: Say: 'I love this card, but cannot justify the annual fee given competitor zero-fee offers. Are there any retention credits or statement offers available?'",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "100% Annual Fee Reimbursed or 20,000+ Bonus Points Offered\nWorks 80%+ of the time if your account is in good standing.",
        "b3": "money",
        "script": "Never pay a credit card annual fee without making this two-minute phone call first. When your annual fee posts, call customer service and navigate to the cancellation department. When the retention representative picks up, do not yell. Use this exact phrase: I really enjoy using your card, but with other premium cards offering fee waivers, I cannot justify paying this annual fee. Do you have any retention offers or statement credits to keep my account active? Retention departments have secret budgets to keep cardholders. Eight times out of ten, they will either waive the entire fee or give you enough bonus points to cover it. Save this script for your next bill.",
        "tags": ["credit card annual fee", "retention call script", "waive credit card fee", "credit card rewards", "personal finance hacks", "wealth blueprint"],
        "pinned_comment": "Have you ever negotiated your credit card annual fee? Comment your result below!"
    },
    {
        "id": 30,
        "region": "INDIA",
        "category": "Retirement Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "EPF vs. VPF: The 8.25% Guaranteed Risk-Free Tax Shield 🛡️💵",
        "sub": "How salaried employees get 8.25% sovereign interest with zero market risk",
        "c1_t": "THE FIXED DEPOSIT TAX TRAP",
        "c1_d": "Bank FDs offer 7% interest, but that interest is added to your income and taxed at your slab rate (up to 30%+), reducing your real return to barely 4.9% (below inflation).",
        "b1": "warning",
        "c2_t": "VOLUNTARY PROVIDENT FUND (VPF)",
        "c2_d": "Step 1: Ask your company HR to activate Voluntary Provident Fund (VPF).\nStep 2: You can allocate up to 100% of your Basic + DA to VPF.\nStep 3: Earn the same sovereign-guaranteed 8.25% rate as your regular EPF.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "8.25% Sovereign-Guaranteed Interest Backed by Govt of India\nTax-free interest up to ₹2,50,000 annual employee contribution!",
        "b3": "money",
        "script": "If you are a salaried employee in India putting extra savings into bank fixed deposits, you are quietly losing purchasing power. Bank FD interest gets chopped by up to 30 percent in income tax. Instead, talk to your HR payroll department and ask to activate VPF—the Voluntary Provident Fund. VPF allows you to contribute beyond the mandatory 12 percent EPF deduction, all the way up to 100 percent of your basic pay. You get the exact same 8.25 percent sovereign-guaranteed interest rate backed by the Government of India, and your interest is completely tax-free up to 2.5 lakh rupees of annual contributions. Save this reel and notify your HR before the next payroll cycle.",
        "tags": ["vpf vs epf", "provident fund hack", "salaried tax savings", "high interest fixed return", "smart money india", "wealth blueprint"],
        "pinned_comment": "Are you using VPF to beat bank fixed deposits? Comment below!"
    },
    {
        "id": 31,
        "region": "GLOBAL",
        "category": "Asset Protection",
        "voice": "en-US-ChristopherNeural",
        "title": "The Umbrella Insurance Secret: $1,000,000 Shield for $20/Mo 🛡️🏰",
        "sub": "How the wealthy protect their homes & stock portfolios from devastating lawsuits",
        "c1_t": "THE AUTO & HOME LIMIT TRAP",
        "c1_d": "Standard auto and home policies max out at $250,000 to $500,000 in liability. In a serious car accident or property injury, lawyers sue for your future wages, house, and stock portfolio.",
        "b1": "warning",
        "c2_t": "THE PERSONAL UMBRELLA POLICY",
        "c2_d": "Step 1: Contact your existing auto/home insurer.\nStep 2: Add a $1,000,000 to $2,000,000 Personal Umbrella Policy.\nStep 3: It sits on top of all policies and pays lawyers' defense fees.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "$1,000,000 in Extra Legal Shielding for only ~$20/Month!\nProtects your 401(k), home equity, and future salary.",
        "b3": "money",
        "script": "If your net worth is over 100,000 dollars and you do not have an umbrella insurance policy, you are one bad car accident away from bankruptcy. Standard auto and home insurance liability caps out around 300,000 dollars. If you cause an accident with an expensive vehicle or someone gets seriously injured on your property, trial lawyers will sue for your home equity, your brokerage accounts, and your future earnings. But you can buy a 1 million dollar personal umbrella policy for literally 15 to 20 dollars a month. It kicks in when your standard insurance maxes out and pays for your legal defense team. It is the cheapest wealth protection in the world. Save this before you need it.",
        "tags": ["umbrella insurance", "wealth protection", "asset protection", "lawsuit defense", "financial literacy", "wealth blueprint"],
        "pinned_comment": "Do you have an umbrella policy? Comment below and follow The Wealth Blueprint!"
    },
    {
        "id": 32,
        "region": "INDIA",
        "category": "Insurance Defense",
        "voice": "en-IN-PrabhatNeural",
        "title": "The Health Insurance Room Rent Capping Trap 🏥❌ #InsuranceSecret",
        "sub": "Why choosing a luxury hospital room can cut your claim payout by 50%",
        "c1_t": "THE 1% ROOM RENT TRAP",
        "c1_d": "Most cheap health policies limit room rent to 1% of your sum insured (e.g. ₹5,000/day on a ₹5 Lakh cover). If you pick an ₹8,000/day deluxe room, insurers apply proportional deduction across ALL medical bills.",
        "b1": "warning",
        "c2_t": "NO ROOM RENT CAPPING ADD-ON",
        "c2_d": "Step 1: Check your policy document for 'Room Rent Limit'.\nStep 2: Choose a plan with 'Single Private Room' or 'No Room Rent Capping'.\nStep 3: Doctor fees, surgery, and ICU charges will be paid at 100% without deductions.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves ₹1,00,000 to ₹3,00,000 in Out-of-Pocket Hospital Bills\nZero proportional deduction penalties on surgeries.",
        "b3": "money",
        "script": "When you get hospitalized, picking a private room can quietly cost you hundreds of thousands of rupees even with health insurance. Here is how the room rent capping trap works. Many policies cap room rent at 1 percent of your sum insured. If your cover is 5 lakh rupees, your room limit is 5,000 rupees a day. If you choose an 8,000 rupee private room, the insurance company will not just deduct the room difference—they will apply a proportionate deduction to your entire surgery, doctor visits, and ICU bill. A 4 lakh hospital bill can end up paying out barely 2.5 lakhs. Always choose a policy with no room rent capping or single private room eligibility. Share this with your family to avoid surprise medical bills.",
        "tags": ["health insurance", "room rent capping", "insurance claim hack", "medical bills", "smart money india", "wealth blueprint"],
        "pinned_comment": "Check your health insurance room rent clause right now! Save this reel for later."
    },
    {
        "id": 33,
        "region": "GLOBAL",
        "category": "Credit Arbitrage",
        "voice": "en-US-ChristopherNeural",
        "title": "The 45-Day Interest-Free Float (Earn Passive Yield on Bank Money) 💳📈",
        "sub": "How to legally earn 7% yield on money you haven't even paid your credit card yet",
        "c1_t": "PAYING BILLS IMMEDIATELY",
        "c1_d": "Paying off your credit card charges the same day you swipe gives banks free liquidity. Your cash sits in 0.01% checking accounts doing nothing for 30 days.",
        "b1": "warning",
        "c2_t": "THE 45-DAY HIGH-YIELD FLOAT",
        "c2_d": "Step 1: Swipe all monthly living expenses on your credit card on Day 1 of the billing cycle.\nStep 2: Keep your monthly expense cash parked in a 5% High-Yield Savings or 7% Liquid Fund.\nStep 3: Set auto-pay on the due date (Day 45) to capture 45 days of risk-free compound interest.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Earn $300 to $1,000 in Free Annual Interest on Everyday Spending\nBoosts liquidity while building perfect on-time payment history.",
        "b3": "bull",
        "script": "If you pay off your credit card immediately after every purchase, you are missing out on free interest payments. Credit cards give you an interest-free grace period of up to 45 to 50 days between your purchase date and your actual due date. The wealthy take full advantage of this float. When you make purchases, keep that cash parked in a high-yield savings account or overnight liquid fund earning 5 to 7 percent interest. Set up auto-pay in full on your due date. You earn free risk-free interest on the bank's money for over six weeks, while pocketing 2 to 5 percent in cashback rewards. Save this reel and automate your float today.",
        "tags": ["credit card float", "grace period arbitrage", "high yield savings", "earn passive interest", "credit card rewards", "wealth blueprint"],
        "pinned_comment": "Are you using the 45-day credit float? Comment your favorite card below!"
    },
    {
        "id": 34,
        "region": "INDIA",
        "category": "Travel Protection",
        "voice": "en-IN-PrabhatNeural",
        "title": "DGCA Flight Delay Rule: Get 100% Cash Refunds + Free Meals ✈️💸",
        "sub": "The mandatory aviation rights airlines secretly hide on domestic Indian flights",
        "c1_t": "AIRLINE VOUCHER SCAM",
        "c1_d": "When airlines delay or cancel flights, they offer worthless food vouchers or non-refundable airline credit. Most passengers accept them without knowing civil aviation regulations.",
        "b1": "warning",
        "c2_t": "DGCA PASSENGER CHARTER CAR SECTION 3",
        "c2_d": "Step 1: Flight delayed > 2 hours? Airline must provide free meals and refreshments.\nStep 2: Flight delayed > 6 hours? Airline must offer alternative flight or 100% full cash refund.\nStep 3: Flight canceled without 2 weeks notice? Up to ₹10,000 legal compensation.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Up to ₹10,000 Cash Compensation + Free Alternative Flight\nCash refund back to your original payment mode, not airline credits.",
        "b3": "money",
        "script": "Next time IndiGo, Air India, or SpiceJet delays your flight, do not just sit in the waiting lounge frustrated. The Directorate General of Civil Aviation has a strict passenger charter. If your flight is delayed over two hours, the airline is legally required to provide free meals and refreshments at the gate. If the delay exceeds six hours, you are entitled to either a free alternative flight or a full 100 percent cash refund back to your bank account—not airline credit vouchers. And if they cancel your flight without giving at least two weeks prior notice, they must pay you up to 10,000 rupees in direct cash compensation. Save this reel so you have the DGCA rule ready at the airport counter.",
        "tags": ["dgca rules", "flight delay compensation", "indian aviation law", "indigo flight delay", "passenger rights", "wealth blueprint"],
        "pinned_comment": "Ever had a delayed flight in India? Save this reel for your next trip!"
    },
    {
        "id": 35,
        "region": "INDIA",
        "category": "Credit Protection",
        "voice": "en-IN-PrabhatNeural",
        "title": "RBI 3-Day Credit Card Grace Period (Avoid Late Fees & CIBIL Hit) 💳⏳",
        "sub": "The mandatory central bank rule that gives you 72 extra hours after your due date",
        "c1_t": "THE 1-DAY DUE DATE PANIC",
        "c1_d": "Banks charge ₹750 to ₹1,300 late fees plus 42% APR interest if you miss your due date by a single second. They also threaten to report negative marks to CIBIL.",
        "b1": "warning",
        "c2_t": "RBI MASTER DIRECTION ON CREDIT CARDS",
        "c2_d": "Step 1: Check RBI Circular RBI/2022-23/29 Master Direction Clause 10(b).\nStep 2: Banks are strictly forbidden from levying late payment charges until 3 DAYS after due date.\nStep 3: No default can be reported to credit bureaus during this 3-day buffer.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Zero Late Fees and Zero 42% Penalty APR Charged\n100% Protection of your 750+ CIBIL credit score.",
        "b3": "money",
        "script": "If you forgot to pay your credit card bill yesterday, do not panic and do not let the bank bully you into paying late fees. Under Reserve Bank of India Master Directions, every credit card issuer in India must provide a mandatory three-day grace period past your official due date. If your payment was due on the tenth, the bank is legally barred from levying any late payment penalties or reporting a default to CIBIL until after the thirteenth. If your bank automatically charged a late fee during these three days, quote the RBI Master Direction and demand an immediate reversal. Save this reel so you never pay illegal bank fees.",
        "tags": ["rbi grace period", "credit card late fee", "cibil score protection", "banking rules india", "personal finance tips", "wealth blueprint"],
        "pinned_comment": "Did your bank ever charge you a late fee within 3 days? Demand a refund!"
    },
    {
        "id": 36,
        "region": "INDIA",
        "category": "Tax Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "Section 80CCD(1B): The Extra ₹50,000 NPS Tax Shield 🛡️💰",
        "sub": "How to save an extra ₹15,600 in cash tax over and above Section 80C limits",
        "c1_t": "THE ₹1.5 LAKH 80C CEILING",
        "c1_d": "Most taxpayers max out their ₹1,50,000 Section 80C limit with EPF and term insurance, then stop saving taxes thinking there are zero other deductions left.",
        "b1": "warning",
        "c2_t": "SECTION 80CCD(1B) NPS ALLOCATION",
        "c2_d": "Step 1: Open a National Pension Scheme (NPS) Tier-1 account online via eNPS.\nStep 2: Invest ₹50,000 annually into equity-heavy auto-choice (75% equity).\nStep 3: Claim an exclusive ₹50,000 deduction on top of your ₹1.5L 80C deduction.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves ₹15,600 Direct Cash Tax Every Year (in 30% tax bracket)\nCompounds at 10-12% historically into a multi-crore pension corpus.",
        "b3": "bull",
        "script": "If you are in the 30 percent tax bracket in India and only claim Section 80C, you are leaving over fifteen thousand rupees in cash on the table every single year. Section 80C caps out at 1.5 lakh rupees, but Section 80CCD subsection 1B gives you an exclusive, extra 50,000 rupee tax deduction specifically for National Pension Scheme Tier-1 accounts. Contributing 50,000 rupees into NPS directly saves you 15,600 rupees in hard cash tax, while the money compounds in low-cost index funds at market returns with the lowest fund management charges in the world. Save this reel and max out your 80CCD before March thirty-first.",
        "tags": ["section 80ccd", "nps tax deduction", "save income tax", "tax saving hacks", "indian tax planning", "wealth blueprint"],
        "pinned_comment": "Are you utilizing the extra ₹50K NPS deduction? Comment below!"
    },
    {
        "id": 37,
        "region": "INDIA",
        "category": "Real Estate Math",
        "voice": "en-IN-PrabhatNeural",
        "title": "Budget 2024 Real Estate Tax Rule: 12.5% vs 20% Indexation Hack 🏠📊",
        "sub": "How to legally choose the lowest property tax between the new and old tax rates",
        "c1_t": "THE INDEXATION REMOVAL PANIC",
        "c1_d": "When Budget 2024 cut property LTCG from 20% to 12.5% but removed indexation, millions feared massive tax bills on ancestral or older properties.",
        "b1": "warning",
        "c2_t": "THE AMENDED GRANDFATHERING RULE",
        "c2_d": "Step 1: Did you buy or acquire property BEFORE July 23, 2024?\nStep 2: You are legally entitled to calculate tax BOTH ways: 12.5% without indexation vs 20% with indexation.\nStep 3: Pay whichever option results in the lower tax bill!",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves ₹5,00,000 to ₹25,00,000 in Capital Gains on Old Properties\n100% Legal amendment passed in the Finance Act 2024.",
        "b3": "money",
        "script": "If you are selling a house or plot in India bought before July 2024, do not pay 12.5 percent tax blindly. When the government removed indexation in Budget 2024, public pushback forced an immediate amendment. If you acquired your property before July 23, 2024, you have the legal right to compute your long-term capital gains tax under both methods: 12.5 percent without indexation, or 20 percent with full indexation benefit. You simply pay whichever tax amount is lower. On properties held for over 10 years, indexation often reduces your taxable profit to near zero. Save this reel and verify your tax calculation with your CA.",
        "tags": ["property tax indexation", "budget 2024 real estate", "capital gains property", "indian real estate tax", "save tax on home sale", "wealth blueprint"],
        "pinned_comment": "Selling property soon? Make sure your CA runs both calculations!"
    },
    {
        "id": 38,
        "region": "INDIA",
        "category": "Tax Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "Section 54EC Bonds: Save ₹10 Lakhs Tax on Land & House Sales 🏛️🪙",
        "sub": "How to shield up to ₹50 Lakhs in real estate capital gains without buying another house",
        "c1_t": "THE FORCED PROPERTY REINVESTMENT",
        "c1_d": "People think the only way to avoid LTCG on property sale is to buy another expensive house under Section 54. But what if you don't want more illiquid real estate?",
        "b1": "warning",
        "c2_t": "SECTION 54EC CAPITAL GAIN BONDS",
        "c2_d": "Step 1: Sell land or building and identify your net capital gains.\nStep 2: Within 6 months of sale, invest up to ₹50 Lakhs into NHAI, REC, PFC, or IRFC 54EC bonds.\nStep 3: Lock in for 5 years and pay exactly 0% capital gains tax.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Save Up to ₹10,00,000 in Direct Capital Gains Taxes\nEarn ~5.25% annual government-guaranteed sovereign interest.",
        "b3": "money",
        "script": "When you sell a plot of land or residential building in India, you do not have to buy another house just to save capital gains tax. Under Section 54EC of the Income Tax Act, you can take up to 50 lakh rupees of your long-term capital gain and invest it into specified government infrastructure bonds like NHAI or Rural Electrification Corporation. You have six months from the sale date to invest. The bonds are locked for five years, pay 5.25 percent annual interest guaranteed by the government, and completely eliminate your capital gains tax bill. Save this reel for when you sell any property.",
        "tags": ["section 54ec", "capital gain bonds", "nhai bonds", "save property tax", "indian real estate tax", "wealth blueprint"],
        "pinned_comment": "Did you know about 54EC bonds? Save this reel for your next property sale!"
    },
    {
        "id": 39,
        "region": "INDIA",
        "category": "Consumer Trap",
        "voice": "en-IN-PrabhatNeural",
        "title": "The No-Cost EMI Deception: The Hidden 18% GST & Processing Fee Scam ❌📱",
        "sub": "Why 'Zero Percent Interest' purchases actually cost you thousands more than paying cash",
        "c1_t": "THE ZERO PERCENT INTEREST ILLUSION",
        "c1_d": "E-commerce sites advertise 'No-Cost EMI' on smartphones and laptops. In reality, the bank gives you a front-end discount equal to interest, then charges normal interest month by month.",
        "b1": "warning",
        "c2_t": "THE HIDDEN CHARGES BREAKDOWN",
        "c2_d": "Step 1: The bank charges 18% GST on the monthly interest component (never discounted).\nStep 2: A mandatory 'EMI Processing Fee' of ₹199 to ₹299 + GST is charged on Day 1.\nStep 3: If you prepay or cancel, the merchant discount is clawed back.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves ₹1,500 to ₹4,500 in Hidden Fees & Taxes on Big Purchases\nPay upfront with cashback cards or debit to capture true discounts.",
        "b3": "money",
        "script": "There is no such thing as a free lunch, and there is definitely no such thing as a No-Cost EMI. When Amazon or Flipkart offers No-Cost EMI, the bank does not lend money for free. The retailer gives you an upfront discount equal to the interest amount. But here is the catch: you still have to pay eighteen percent GST on every monthly interest charge on your credit card statement, and banks slap a hidden 199 to 299 rupee processing fee on your first bill. On an 80,000 rupee laptop, you quietly lose up to 3,000 rupees in pure phantom fees. Pay in full with a cashback card instead. Share this with anyone shopping on EMI.",
        "tags": ["no cost emi trap", "credit card emi scam", "hidden gst charges", "flipkart emi", "amazon sale hacks", "wealth blueprint"],
        "pinned_comment": "Ever noticed the extra GST on your No-Cost EMI statement? Check your bill!"
    },
    {
        "id": 40,
        "region": "INDIA",
        "category": "Tax Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "Section 80D Preventive Checkup: ₹5,000 Cash Tax Deduction 🏥🧾",
        "sub": "How to claim ₹5,000 tax deduction with simple cash receipts even without health insurance",
        "c1_t": "THE EXPENSIVE INSURANCE LIMITATION",
        "c1_d": "Many people don't buy private health insurance because of high premiums, missing out entirely on Section 80D tax benefits that salaried employees get.",
        "b1": "warning",
        "c2_t": "PREVENTIVE HEALTH CHECKUP CLAUSE",
        "c2_d": "Step 1: Book routine blood tests, full-body health checks, or dental checkups.\nStep 2: Section 80D allows up to ₹5,000 deduction for preventive health checkups.\nStep 3: Unlike regular insurance premiums, this ₹5,000 deduction is valid even if paid in CASH!",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves Up to ₹1,560 in Hard Cash Tax Every Year\nCovers checkups for yourself, spouse, children, and parents.",
        "b3": "money",
        "script": "Did you know you can claim a 5,000 rupee income tax deduction for simply getting a routine blood test or full-body health checkup? Under Section 80D of the Income Tax Act, taxpayers can claim up to 5,000 rupees every financial year for preventive health checkups. And here is the special rule: while regular health insurance premiums must be paid digitally to qualify for deductions, preventive checkups are legally allowed to be paid in cash. Just preserve the clinic invoice or diagnostic lab bill. It covers tests for you, your spouse, your kids, and your parents. Save this reel and add it to your tax filing this year.",
        "tags": ["section 80d", "preventive health checkup", "income tax deduction", "save tax india", "health test deduction", "wealth blueprint"],
        "pinned_comment": "Did you claim your ₹5,000 preventive checkup deduction? Save this reel!"
    },
    {
        "id": 41,
        "region": "INDIA",
        "category": "Banking Shield",
        "voice": "en-IN-PrabhatNeural",
        "title": "The RBI 3-Day Cyber Fraud Rule: 100% Refund on Unauthorized Transactions 🚨🏦",
        "sub": "The central bank mandate that forces banks to credit scammed money within 10 days",
        "c1_t": "THE 'OTP WAS SENT' EXCUSE",
        "c1_d": "When victims report phishing or unauthorized card swipes, bank call centers immediately say: 'You are liable because SMS was sent.' Victims give up their life savings.",
        "b1": "warning",
        "c2_t": "RBI ZERO-LIABILITY CIRCULAR (DBR.No.Leg.BC.78)",
        "c2_d": "Step 1: If third-party fraud occurs through zero fault of yours, report within 3 DAYS.\nStep 2: Under RBI rules, your liability is EXACTLY ZERO rupees.\nStep 3: The bank must credit the disputed amount as shadow balance within 10 working days.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "100% Reversal of Stolen Funds by Bank\nBank must resolve claim within 90 days without harassing the depositor.",
        "b3": "money",
        "script": "If you wake up and see unauthorized transactions debited from your bank account or credit card, do not waste time crying. Act within seventy-two hours. Under the Reserve Bank of India Zero Liability directive, if money is stolen due to third-party cyber fraud or bank system negligence and you notify your bank within three working days, your financial liability is exactly zero rupees. Furthermore, the bank is legally mandated to credit the full stolen amount back into your account within ten working days, even while their fraud team is still investigating. Save this reel right now—it could save your entire life savings tomorrow.",
        "tags": ["rbi fraud rules", "unauthorized transaction refund", "cyber scam recovery", "banking safety india", "zero liability circular", "wealth blueprint"],
        "pinned_comment": "Save this reel immediately. If you ever get scammed, report it within 72 hours!"
    },
    {
        "id": 42,
        "region": "INDIA",
        "category": "Tax Arbitrage",
        "voice": "en-IN-PrabhatNeural",
        "title": "Corporate Car Lease Policy: Slash 30% Tax & GST on Your Dream Car 🚗💼",
        "sub": "How high-earning corporate employees save ₹3 to ₹5 Lakhs on new vehicle purchases",
        "c1_t": "BUYING A CAR WITH POST-TAX SALARY",
        "c1_d": "Buying a car with personal car loans uses after-tax income (taxed at 30%+), plus you pay 28% GST + cess on the car with zero ability to claim depreciation or fuel write-offs.",
        "b1": "warning",
        "c2_t": "COMPANY CAR LEASE PERK",
        "c2_d": "Step 1: Ask HR if your company offers a 'Corporate Car Lease Scheme'.\nStep 2: The company leases the car; monthly EMI is deducted directly from PRE-TAX gross salary.\nStep 3: Fuel bills, driver salary, and maintenance are also reimbursed tax-free.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Saves ₹3,00,000 to ₹7,00,000 over 3-4 Year Lease Term\nEffectively gets you a 30% flat discount on vehicle cost + zero fuel tax.",
        "b3": "money",
        "script": "If you earn more than twenty lakh rupees a year in India and want to buy a car, never take a standard retail car loan from a bank. Instead, check if your employer offers a Corporate Car Lease Program. Under a corporate lease, the monthly vehicle EMI is deducted directly from your pre-tax salary before income tax is calculated. On top of that, your monthly fuel, insurance, and routine maintenance bills are paid as tax-free reimbursements. You effectively get a thirty percent discount on the vehicle cost and save upwards of five lakh rupees across four years compared to buying the car personally. Check your HR benefits portal today.",
        "tags": ["corporate car lease", "save tax on car", "salary restructuring", "tax hacks india", "smart money corporate", "wealth blueprint"],
        "pinned_comment": "Does your company have a car lease policy? Comment below!"
    },
    {
        "id": 43,
        "region": "INDIA",
        "category": "Debt Freedom",
        "voice": "en-IN-PrabhatNeural",
        "title": "The 1-Extra-EMI Hack: Slash 6 Years & ₹15 Lakhs Off Your Home Loan 🏡📉",
        "sub": "The simple prepayment mathematical hack that cuts a 20-year mortgage down to 14 years",
        "c1_t": "THE 20-YEAR INTEREST TRAP",
        "c1_d": "On a ₹50 Lakh home loan at 9% for 20 years, you pay ₹58 Lakhs in pure interest! You literally pay the bank more in interest than the entire house originally cost.",
        "b1": "warning",
        "c2_t": "THE 1-EXTRA-EMI PREPAYMENT BLUEPRINT",
        "c2_d": "Step 1: Set an auto-debit to pay just ONE additional EMI each calendar year.\nStep 2: Ensure the extra payment is tagged strictly to reduce loan PRINCIPAL, not interest.\nStep 3: Alternatively, increase your monthly EMI by just 5% every year with appraisals.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Cuts Loan Tenure from 20 Years Down to 14 Years\nSaves Over ₹15,00,000 in Cold Hard Cash Interest!",
        "b3": "bull",
        "script": "If you have a 20-year home loan in India, here is a financial truth that will shock you. Over twenty years, you will pay the bank more in interest than the original loan amount itself. On a 50 lakh rupee loan at 9 percent, you pay nearly 58 lakhs in interest. But you can destroy this loan with one simple move: pay just one extra EMI per year. By making thirteen EMI payments instead of twelve, you shave six full years off your loan tenure and save more than fifteen lakh rupees in interest payments. The bank loses, and you become debt-free six years earlier. Share this with anyone who has a home loan.",
        "tags": ["home loan prepayment", "save home loan interest", "debt free faster", "emi prepayment hack", "mortgage hack india", "wealth blueprint"],
        "pinned_comment": "Are you prepaying your home loan? Comment your strategy below!"
    },
    {
        "id": 44,
        "region": "GLOBAL",
        "category": "Retirement Shield",
        "voice": "en-US-ChristopherNeural",
        "title": "The HSA Triple Tax Advantage: The Ultimate Stealth Retirement Account 🏥📈",
        "sub": "Why the Health Savings Account beats both the 401(k) and Roth IRA for building wealth",
        "c1_t": "THE SPEND-IT-ALL HEALTH TRAP",
        "c1_d": "Most people treat HSAs like FSAs, spending balance on band-aids and aspirins every December because they don't realize HSA funds roll over forever and can be invested.",
        "b1": "warning",
        "c2_t": "THE TRIPLE-TAX-FREE COMPOUND ENGINE",
        "c2_d": "Step 1: Open a high-deductible health plan (HDHP) with an HSA.\nStep 2: Max out contributions ($4,150 single / $8,300 family for 2024).\nStep 3: Invest 100% in S&P 500 index funds and pay medical out-of-pocket while keeping receipts.",
        "b2": "growth",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Triple Tax-Free: 1. Tax-free in, 2. Tax-free growth, 3. Tax-free out!\nAt age 65, functions exactly like a traditional IRA for non-medical expenses.",
        "b3": "money",
        "script": "The single best retirement account in the United States is not a 401(k) or a Roth IRA. It is a Health Savings Account. The HSA is the only account in the tax code with a triple-tax advantage: your contributions are 100 percent tax-deductible going in, your investments grow 100 percent tax-free, and your withdrawals are completely tax-free for qualified medical expenses. If you pay routine medical costs out of pocket and save your receipts, you can invest your HSA in index funds for 30 years and withdraw tax-free later. After age 65, you can withdraw for anything penalty-free. It is a stealth retirement super-weapon. Save this reel and max your HSA.",
        "tags": ["hsa account", "triple tax advantage", "health savings account", "retirement planning", "stealth ira", "wealth blueprint"],
        "pinned_comment": "Are you investing your HSA or spending it? Comment below!"
    },
    {
        "id": 45,
        "region": "INDIA",
        "category": "Credit Protection",
        "voice": "en-IN-PrabhatNeural",
        "title": "Credit Card 'Settled' vs 'Closed': The 7-Year CIBIL Poison Pill 💳☠️",
        "sub": "Why accepting a one-time settlement offer from a bank destroys your credit for seven years",
        "c1_t": "THE TEMPTING ONE-TIME SETTLEMENT",
        "c1_d": "When you struggle with credit card debt, banks offer: 'Pay 40% now and we settle the account.' Desperate borrowers agree, thinking their problem is solved.",
        "b1": "warning",
        "c2_t": "THE 'SETTLED' STATUS DAMAGE",
        "c2_d": "Step 1: The bank writes off remaining debt as a loss and reports status as 'SETTLED'.\nStep 2: Future lenders view 'Settled' as a partial default; home and car loans get rejected instantly.\nStep 3: Always insist on full payment with waived interest to get a 'CLOSED' status certificate.",
        "b2": "card",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Protects CIBIL Score from a 100-Point Crash\nGuarantees future eligibility for home loans and business credit.",
        "b3": "money",
        "script": "If you are struggling with credit card debt, never agree to a bank settlement before watching this. When you are late on payments, recovery agents will say: Just pay thirty thousand rupees and we will settle your one lakh rupee balance. It sounds like a blessing, but it is a trap. The bank will report your account status to CIBIL as Settled, not Closed. A Settled status is a permanent red flag telling every future bank that you defaulted on what you owed. Your score will plummet, and you will be blacklisted from home loans, car loans, and credit cards for up to seven years. Always negotiate to waive interest and obtain a No Due Certificate marked Closed. Save this reel.",
        "tags": ["cibil settlement trap", "credit card settled vs closed", "improve cibil score", "debt settlement truth", "loan rejection reason", "wealth blueprint"],
        "pinned_comment": "Check your CIBIL report right now for any 'Settled' accounts! Save this reel."
    },
    {
        "id": 46,
        "region": "INDIA",
        "category": "Gold Arbitrage",
        "voice": "en-IN-PrabhatNeural",
        "title": "Gold Monetization Scheme (GMS): Earn 2.5% Tax-Free Gold Return 🪙🏛️",
        "sub": "How Indian households turn idle locker jewelry into government-paid gold interest",
        "c1_t": "THE DEAD GOLD IN LOCKERS",
        "c1_d": "Indian households hold 25,000 tonnes of gold in bank lockers. You pay ₹5,000/yr in locker rent while that physical gold generates zero cash flow and faces theft risks.",
        "b1": "warning",
        "c2_t": "REVISE UNDER GOLD MONETIZATION SCHEME (GMS)",
        "c2_d": "Step 1: Take idle coins, bars, or broken jewelry to an SBI or PNB authorized collection center.\nStep 2: Gold is melted, assayed, and deposited in GMS for 1 to 15 years.\nStep 3: Earn up to 2.5% annual interest paid in GOLD or cash, backed by Central Govt.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Earn 2.5% Free Gold Return + 0% Capital Gains Tax + 0% Income Tax\nEliminate locker fees while gold quantity compounds risk-free.",
        "b3": "bull",
        "script": "Did you know you can deposit your idle gold jewelry into a bank and earn guaranteed annual interest on it? Under the Government of India's Gold Monetization Scheme, you can take idle jewelry, coins, or bars to authorized banks like SBI. The bank assays your gold and holds it in a gold savings account. You earn up to 2.5 percent annual interest paid in pure gold or cash. Best of all, all earnings and maturity proceeds are completely exempt from income tax and capital gains tax. Instead of paying locker rent on idle gold, your gold compounds and earns passive income backed by the government. Save this reel and tell your parents.",
        "tags": ["gold monetization scheme", "earn on idle gold", "gms sbi gold deposit", "gold interest rate", "indian gold investment", "wealth blueprint"],
        "pinned_comment": "Do you have idle gold in bank lockers? Save this reel and look into GMS!"
    },
    {
        "id": 47,
        "region": "INDIA",
        "category": "Salaried Rights",
        "voice": "en-IN-PrabhatNeural",
        "title": "The Gratuity 4-Year-240-Day Rule: Claim Full Gratuity Early 💼💰",
        "sub": "The legal labor court precedent that entitles employees to gratuity before completing 5 years",
        "c1_t": "THE STRICT 5-YEAR MYTH",
        "c1_d": "HR departments tell resigning employees: 'You worked 4 years and 10 months, so you get ZERO gratuity because you didn't finish 5 full years.' Millions lose lakhs.",
        "b1": "warning",
        "c2_t": "SECTION 2A PAYMENT OF GRATUITY ACT",
        "c2_d": "Step 1: Check Section 2A of the Payment of Gratuity Act 1972.\nStep 2: 'Continuous service' requires only 240 days of work in the 5th year (190 days for 5-day week companies).\nStep 3: Supreme Court & High Court rulings confirm: 4 years and 240 days qualifies for full gratuity payout.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Unlocks ₹1,50,000 to ₹5,00,000 in Legal Gratuity Payouts\nCompany cannot legally withhold gratuity after 4 years 240 days.",
        "b3": "money",
        "script": "If you are resigning from your corporate job, do not let HR cheat you out of your gratuity. Most HR managers will tell you that gratuity is only payable if you complete five full years. That is false. Under Section 2A of the Payment of Gratuity Act and numerous High Court judgments, an employee who completes four years and two hundred and forty days of continuous service is legally entitled to full gratuity. If your company operates on a five-day work week, the threshold is even lower—just one hundred and ninety days in your fifth year. That can mean two to five lakh rupees in your bank account that you would otherwise leave behind. Save this reel and cite Section 2A to your HR.",
        "tags": ["gratuity rule india", "4 years 240 days gratuity", "payment of gratuity act", "employee rights india", "corporate salary secrets", "wealth blueprint"],
        "pinned_comment": "Check your tenure before resigning! Share this with someone switching jobs."
    },
    {
        "id": 48,
        "region": "GLOBAL",
        "category": "Retirement Shield",
        "voice": "en-US-ChristopherNeural",
        "title": "The Backdoor Roth IRA: How High Earners Legally Bypass Income Limits 🛡️💵",
        "sub": "The IRS-approved strategy that allows doctors, tech workers, and founders to invest tax-free",
        "c1_t": "THE ROTH INCOME CLIFF",
        "c1_d": "If you earn over $161,000 single or $240,000 married in 2024, the IRS legally bans you from contributing directly to a Roth IRA. High earners assume tax-free compounding is impossible.",
        "b1": "warning",
        "c2_t": "THE BACKDOOR CONVERSION PROTOCOL",
        "c2_d": "Step 1: Make a non-deductible contribution to a Traditional IRA (no income limits).\nStep 2: Leave cash in core money market for 1 day.\nStep 3: Execute a direct conversion to your Roth IRA. Pay $0 in conversion taxes if you have $0 pre-tax IRA balances.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "$7,000+ Every Year Compounding 100% Tax-Free Forever\nUnlocks tax-free capital gains and tax-free retirement distributions.",
        "b3": "bull",
        "script": "If you make over 160,000 dollars a year, the IRS bars you from opening a Roth IRA directly. But the wealthy have used a legal loophole called the Backdoor Roth IRA for decades. Here is how it works. You open a traditional IRA and make a non-deductible contribution of 7,000 dollars. Traditional IRAs have zero income limits. The very next day, before that money earns any interest, you click convert to Roth IRA in your brokerage dashboard. Because you already paid taxes on that money, the conversion is completely tax-free. You just bypassed the IRS income cap legally and put 7,000 dollars into a tax-free compound machine. Save this reel and talk to your CPA before tax day.",
        "tags": ["backdoor roth ira", "high earner tax hack", "roth ira income limit", "investing strategies", "wealth building tips", "wealth blueprint"],
        "pinned_comment": "Are you doing a Backdoor Roth every year? Comment below!"
    },
    {
        "id": 49,
        "region": "INDIA",
        "category": "Insurance Defense",
        "voice": "en-IN-PrabhatNeural",
        "title": "Term Insurance Increasing Cover: Beat 7% Healthcare & Living Inflation 🛡️📈",
        "sub": "Why a flat ₹1 Crore term cover today will only have the purchasing power of ₹25 Lakhs later",
        "c1_t": "THE INFLATION COVER EROSION",
        "c1_d": "Buying a flat ₹1 Crore cover at age 25 feels massive. But with 6% to 7% inflation, that ₹1 Crore will barely buy ₹25 Lakhs of goods and education when you are 50.",
        "b1": "warning",
        "c2_t": "INCREASING SUM ASSURED OPTION",
        "c2_d": "Step 1: When buying pure term insurance, select 'Increasing Sum Assured' (typically 5% to 10% per year).\nStep 2: Your ₹1 Crore cover automatically expands to ₹2 Crore without extra medical tests.\nStep 3: Premium increases only nominally compared to buying a new policy later in life.",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Family receives ₹2 Crore to ₹3 Crore Inflation-Adjusted Payout\nGuaranteed medical underwriting lock-in while you are young and healthy.",
        "b3": "money",
        "script": "If you bought a flat one crore rupee term insurance policy thinking your family is set for life, you forgot to calculate inflation. At six percent inflation, one crore rupees in twenty-five years will have the purchasing power of barely twenty-five lakh rupees today. If something happens to you down the road, your family will face a massive financial shortfall. When you buy term insurance, always select the Increasing Sum Assured option. This feature automatically increases your death benefit by five to ten percent every year until it doubles, with zero new medical tests or underwriting. It keeps your family genuinely protected against real-world inflation. Save this reel and audit your insurance.",
        "tags": ["term insurance inflation", "increasing sum assured", "life insurance hack", "financial planning india", "smart insurance choice", "wealth blueprint"],
        "pinned_comment": "Check your term insurance policy type right now! Save this reel for reference."
    },
    {
        "id": 50,
        "region": "GLOBAL",
        "category": "Cash Flow Strategy",
        "voice": "en-US-ChristopherNeural",
        "title": "The 3-Bucket Emergency Waterfall: Never Leave Cash in 0.01% Savings 🏦🌊",
        "sub": "How to earn maximum yield on your safety net while maintaining instant same-day access",
        "c1_t": "THE LAZY CHECKING ACCOUNT TRAP",
        "c1_d": "Keeping $20,000 or ₹5 Lakhs sitting in a standard commercial checking account costs you thousands in lost compound yield every single year.",
        "b1": "warning",
        "c2_t": "THE 3-TIER EMERGENCY WATERFALL",
        "c2_d": "Bucket 1: 1 Month Expenses in High-Yield Checking (instant debit/UPI access).\nBucket 2: 2 Months in Ultra-Short Liquid Fund or 5% HYSA (T+1 day access).\nBucket 3: 3 Months in Short-Term Sovereign T-Bills or Sweep FDs (7%+ risk-free yield).",
        "b2": "vault",
        "c3_t": "THE FINANCIAL PAYOFF",
        "c3_d": "Generates $1,000 to $2,500 in Pure Free Passive Interest Annually\nMaintains 100% emergency liquidity without sacrificing buying power to inflation.",
        "b3": "money",
        "script": "Most people handle their emergency funds completely wrong. Either they invest all their money in stocks and have to panic-sell at a loss during an emergency, or they leave 20,000 dollars sitting in a traditional checking account earning zero point zero one percent. Wealthy investors use a three-tier emergency waterfall. Tier one is one month of living expenses in an instant-access high-yield checking account. Tier two is two months of expenses in an overnight liquid fund earning five to seven percent with same-day redemption. Tier three is three months in short-term Treasury bills or sweep fixed deposits. You maintain total emergency protection while capturing thousands in risk-free interest. Save this reel and set up your waterfall.",
        "tags": ["emergency fund strategy", "cash waterfall", "high yield savings", "liquid funds", "personal finance rules", "wealth blueprint"],
        "pinned_comment": "Where do you keep your emergency fund? Comment below!"
    }
]

def build_elite_catalog():
    print("========================================================")
    print("  BUILDING 100X ELITE DEDUPLICATED CATALOG")
    print("========================================================")

    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)

    # Keep posts 1 to 20 intact
    kept_posts = [c for c in existing if c["id"] <= 20]
    print(f"Preserved active posts (1-20): {len(kept_posts)}")

    # Assemble complete clean list with continuous IDs 1 to 50
    final_catalog = list(kept_posts)

    # Map expansion topics
    for item in ELITE_EXPANSION:
        final_catalog.append(item)

    # Ensure IDs are perfectly sequential 1 to N
    for idx, item in enumerate(final_catalog, start=1):
        item["id"] = idx

    print(f"Total deduplicated elite catalog size: {len(final_catalog)}")

    # Verify uniqueness of titles
    titles = [c["title"].lower().strip() for c in final_catalog]
    if len(titles) != len(set(titles)):
        print("[!] WARNING: Duplicate titles detected!")
    else:
        print("[✓] 100% Unique Titles Confirmed across all entries.")

    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(final_catalog, f, indent=2, ensure_ascii=False)

    print(f"[✓] Saved updated catalog to {CATALOG_PATH}")

if __name__ == "__main__":
    build_elite_catalog()
